### ISSUE TITLE
Do not force Java compatibility

### ISSUE THREAD

**Issue by rok5ek** [mxalbert1996/jacoco-android-gradle-plugin#2]
Please remove the following since it is conflicting with newer Java versions e.g. 17.

```java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType<KotlinCompile> {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_11)
    }
}

**Comment by mxalbert1996** [comment]
Not really. This means you need **at least** JDK 11, and newer versions are also okay.
The project itself is built and tested with JDK 17 (see [here](https://github.com/mxalbert1996/jacoco-android-gradle-plugin/blob/main/.github/workflows/test.yml#L35)), and I'm using it in my project which uses JDK 17.

If you found any incompatibility, please describe your issue specifically.

**Comment by rok5ek** [comment]
@mxalbert1996 You are correct it was a mistake in my code. Please feel free to delete this issue.
