### ISSUE TITLE
Enable MultiModule report

### ISSUE THREAD

**Issue by zenyagami** [mxalbert1996/jacoco-android-gradle-plugin#6]
Is any way to enable jacoco for multi module project for example
--app
--domain
---data
If I use the plugin in the `build.gradle` (app module) the report will only scan the app module, is possible to enable the report for other modules?

**Comment by hagi77** [comment]
It's roughly a year later and I assume multi module support has not been implemented, has it?

**Comment by mxalbert1996** [comment]
This is how this plugin works - you apply the plugin to each module you want to enable Jacoco report.
If you are looking for report aggregation, check [gradle-android-test-aggregation-plugin](https://github.com/gmazzo/gradle-android-test-aggregation-plugin) or [Kover](https://github.com/Kotlin/kotlinx-kover).

**Comment by hagi77** [comment]
kover worked like a charm, thank you
